version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directories: 
      - "/"
    schedule:
      interval: "weekly"
      day: saturday
      time: "10:00"
    target-branch: master
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/ftl-build/"
    schedule:
      interval: "weekly"
      day: saturday
      time: "10:00"
    target-branch: master
