name: Editorconfig-Checker
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  editorconfig-checker:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@main # tag v1.0.0 is really out of date

    - name: Run editorconfig-checker
      run: editorconfig-checker
